name: publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm t
      - run: if [[ "$GITHUB_REF" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+\-([^\.]+) ]]; then npm publish --provenance --tag ${BASH_REMATCH[1]} --access public; else npm publish --provenance --access public; fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
