name: version
on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]'
        required: true
      preid:
        description: 'The "prerelease identifier" to use as a prefix for the "prerelease" part of a semver.'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: echo ${{ github.token }} | gh auth login --with-token
      - run: gh auth status
      - run: if [[ -z "${{ github.event.inputs.preid }}" ]]; then npm version ${{ github.event.inputs.newversion }}; else npm version ${{ github.event.inputs.newversion }} --preid ${{ github.event.inputs.preid }}; fi
      - run: git push origin $(git branch --show-current) --tags
